### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by toddwc** [Kadauchi/prolific-assistant#1]
I just posted this review in the Chrome Store, but I wanted to make sure you saw it:

> I absolutely love this extension! Thank you so much.
> 
> However, I noticed that it was eating up a huge chunk of memory, ~200MB, which was more than any other of my extensions or tabs. In comparison, the entire Mturk Suite only uses ~65MB.
> 
> When I disabled Prolific Assistant and then re-enabled it, it was using only 19MB. It's currently using 27MB.
> 
> I'm only semi-techy, but could the extension have a memory leak?

It's now using 32.5MB.

**Comment by Kadauchi** [comment]
It is a possibility, I'll check it out tonight or tomorrow morning. Can you let me know which version of Chrome you are running.

**Comment by toddwc** [comment]
I'm running Chrome 59.0.3071.86 dev (64-bit).

Prolific Assistant is now up to ~81MB.
