### ISSUE TITLE
prolific notifier doesn't work

### ISSUE THREAD

**Issue by fjleon1980** [Kadauchi/prolific-assistant#11]
i am using your prolific notifier (not assistant. well ok i use assistant too but it doesn't work either) tampermonkey script however it doesn't work for me. I never hear the sound despite getting studies. And i made sure the script is showing up as enabled on the tampermonkey extension icon while i leave the tab with prolific loaded up and waiting.

i have seen the code and while i don't understand it at the javascript level i understand what in theory it should do. monitors new elements being added to the page and if it finds one with a class name of list-item then plays the sound. so i don't really know what's happening. this is on latest chrome x64 stable build in windows 10. I have other tabs on the browser that play audio just fine.

**Comment by fjleon1980** [comment]
why are you closing without a comment?

**Comment by Kadauchi** [comment]
Greasyfork has its own issue area: https://greasyfork.org/en/scripts/371224-prolific-alert/feedback

**Comment by fjleon1980** [comment]
i have both your notifier and assistant. neither of them work for me but i saw that you just updated assistant so i will try it out. i think chrome is sleeping off the tab or something because i have seen alerts, but maybe once per 2-3 months and maybe only when i have restarted the machine very recently. and this is with 16gb of ram.
