### ISSUE TITLE
Prolific-Assistant no longer working due to domain change

### ISSUE THREAD

**Issue by Kathxw** [Kadauchi/prolific-assistant#13]
Hello!

Prolific recently changed their domain to https://www.prolific.co/

Could you please update it?

**Comment by fecsa** [comment]
Hello!
I'll join in and confirm!
All this happened on 24.07.2019.

**Comment by fecsa** [comment]
Hi!
Thanks for the quick fix. It is a great help to many users.

**Comment by Kadauchi** [comment]
This has been fixed.
