### ISSUE TITLE
No icon on Firefox

### ISSUE THREAD

**Issue by jurplel** [Kadauchi/prolific-assistant#15]
![image](https://user-images.githubusercontent.com/10716694/62419621-d3e3b580-b652-11e9-9aab-a49ca793b756.png)
Tested on Firefox 68 for macOS and Nightly for Linux

**Comment by Kadauchi** [comment]
It looks like its an issue on Windows as well.

**Comment by Kadauchi** [comment]
Fixed in v3.0.5.
