### ISSUE TITLE
Issues with alert sound

### ISSUE THREAD

**Issue by jurplel** [Kadauchi/prolific-assistant#16]
On chrome, for me, when I change the alert sound it crashes the extension and says that it needs to be repaired. On Firefox it does not do anything at all. If I'm not mistaken, I believe it should be testing the notification sound when I change the alert sound.

**Comment by Kadauchi** [comment]
Thanks for the report. You're correct about what it should be doing.

**Comment by Kadauchi** [comment]
Fixed in v3.0.5.
