### ISSUE TITLE
Being forced to log in over and over

### ISSUE THREAD

**Issue by gennessee** [Kadauchi/prolific-assistant#20]
HI there, I'm having an issue where I keep getting logged out of the site when using prolific assistant. Multiple other people reporting the same problem at [https://www.reddit.com/r/ProlificAc/](https://www.reddit.com/r/ProlificAc/). Thanks for your help!

**Comment by Kadauchi** [comment]
Thanks for letting me know. I'll investigate and try and get a fix out today or tomorrow.

**Comment by Kadauchi** [comment]
Quick update, this hasn't been forgotten.

I've been unable to replicate the issue so far. It looks like its also only affecting some people and not everyone so that makes it harder to track down.

I'll keep trying to figure it out.

**Comment by gennessee** [comment]
So far today, for me at least, it seems to be working properly again. Maybe they fixed something on prolific's side?

**Comment by Kadauchi** [comment]
Seems like this was on Prolific's end and has resolved itself. Feel free to re-open or start a new issue if the login troubles come back.
