### ISSUE TITLE
Extension not working as expected - need an update

### ISSUE THREAD

**Issue by Vioner** [Kadauchi/prolific-assistant#6]
Hi @Kadauchi 
Great work so far! Thank you ;)

Are you planning on updating any time soon? 

I've checked the API URL myself while I had 1 study available (https://www.prolific.ac/api/v1/studies/?current=1)

Unfortunately, regardless of my login status it shows the same thing, f.e 5 studies (1 of them is available to me)

I think it's because Legacy Prolific is no longer available, so my sessionId cookie expired and dissapeared - and therefore -> API must've relied on that.

I guess PA would have to rely on HTML/CSS scraping once again. Am I right?

**Comment by Kadauchi** [comment]
Prolific's new site doesn't allow for HTML scraping in the background unlike their old site. Would have to open a new tab and wait for Prolific's API request to resolve and render to the DOM in that tab in order to scrape.
